In [ ]:
# import packages
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/DSBA 6211/HEMQ.csv')

In [ ]:
# cleaning steps:
cleaing steps:
1. NA imputation
2. dummy variables
3. scale data

SyntaxError: invalid syntax (<ipython-input-5-ffdd917fe810>, line 2)

In [ ]:
# data imputation (decision tree can work with missing values; but this sklearn package cannot work with it)
NA_names =['MORTDUE','VALUE','YOJ','DEROG',
           'DELINQ','CLAGE','NINQ','CLNO','DEBTINC']
df[NA_names]=df[NA_names].fillna(df[NA_names].mean())
df['REASON']=df['REASON'].fillna('DebtCon')
df['JOB']=df['JOB'].fillna('Other')
df.describe(include='all')

BAD          LOAN        MORTDUE          VALUE   REASON  \
count   5960.000000   5960.000000    5960.000000    5960.000000     5960   
unique          NaN           NaN            NaN            NaN        2   
top             NaN           NaN            NaN            NaN  DebtCon   
freq            NaN           NaN            NaN            NaN     4180   
mean       0.199497  18607.969799   73760.817200  101776.048741      NaN   
std        0.399656  11207.480417   42481.395689   56843.931566      NaN   
min        0.000000   1100.000000    2063.000000    8000.000000      NaN   
25%        0.000000  11100.000000   48139.000000   66489.500000      NaN   
50%        0.000000  16300.000000   69529.000000   90000.000000      NaN   
75%        0.000000  23300.000000   88200.250000  119004.750000      NaN   
max        1.000000  89900.000000  399550.000000  855909.000000      NaN   

          JOB          YOJ        DEROG       DELINQ        CLAGE  \
count    5960  5960.000000  5960.000000  5960.000000  5960.000000   
unique      6          NaN          NaN          NaN          NaN   
top     Other          NaN          NaN          NaN          NaN   
freq     2667          NaN          NaN          NaN          NaN   
mean      NaN     8.922268     0.254570     0.449442   179.766275   
std       NaN     7.239301     0.794198     1.071002    83.563059   
min       NaN     0.000000     0.000000     0.000000     0.000000   
25%       NaN     3.000000     0.000000     0.000000   117.371430   
50%       NaN     8.000000     0.000000     0.000000   178.076005   
75%       NaN    12.000000     0.000000     0.449442   227.143058   
max       NaN    41.000000    10.000000    15.000000  1168.233561   

               NINQ         CLNO      DEBTINC  
count   5960.000000  5960.000000  5960.000000  
unique          NaN          NaN          NaN  
top             NaN          NaN          NaN  
freq            NaN          NaN          NaN  
mean       1.186055    21.296096    33.779915  
std        1.653046     9.948280     7.632713  
min        0.000000     0.000000     0.524499  
25%        0.000000    15.000000    30.763159  
50%        1.000000    21.000000    33.779915  
75%        2.000000    26.000000    37.949892  
max       17.000000    71.000000   203.312149

In [ ]:
# generate dummy and combine with the numeric variables together
dummy_data =pd.get_dummies(df[['REASON','JOB']], drop_first=True).astype(int)
print(dummy_data)

      REASON_HomeImp  JOB_Office  JOB_Other  JOB_ProfExe  JOB_Sales  JOB_Self
0                  1           0          1            0          0         0
1                  1           0          1            0          0         0
2                  1           0          1            0          0         0
3                  0           0          1            0          0         0
4                  1           1          0            0          0         0
...              ...         ...        ...          ...        ...       ...
5955               0           0          1            0          0         0
5956               0           0          1            0          0         0
5957               0           0          1            0          0         0
5958               0           0          1            0          0         0
5959               0           0          1            0          0         0

[5960 rows x 6 columns]


In [ ]:
# scaling
X = pd.concat([df.iloc[:,1:4],df.iloc[:,6:13]],axis=1)

names=X.columns

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

scaler.fit(X)
X[names]=scaler.transform(X)

X.describe(include='all')

LOAN      MORTDUE        VALUE          YOJ        DEROG  \
count  5960.000000  5960.000000  5960.000000  5960.000000  5960.000000   
mean      0.197162     0.180378     0.110597     0.217616     0.025457   
std       0.126210     0.106875     0.067040     0.176568     0.079420   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.112613     0.115918     0.068981     0.073171     0.000000   
50%       0.171171     0.169731     0.096708     0.195122     0.000000   
75%       0.250000     0.216705     0.130916     0.292683     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

            DELINQ        CLAGE         NINQ         CLNO      DEBTINC  
count  5960.000000  5960.000000  5960.000000  5960.000000  5960.000000  
mean      0.029963     0.153879     0.069768     0.299945     0.163991  
std       0.071400     0.071529     0.097238     0.140117     0.037639  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.100469     0.000000     0.211268     0.149115  
50%       0.000000     0.152432     0.058824     0.295775     0.163991  
75%       0.029963     0.194433     0.117647     0.366197     0.184555  
max       1.000000     1.000000     1.000000     1.000000     1.000000

In [ ]:
# combine data together
X =pd.concat([X,dummy_data],axis=1)
X.describe()


LOAN      MORTDUE        VALUE          YOJ        DEROG  \
count  5960.000000  5960.000000  5960.000000  5960.000000  5960.000000   
mean      0.197162     0.180378     0.110597     0.217616     0.025457   
std       0.126210     0.106875     0.067040     0.176568     0.079420   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.112613     0.115918     0.068981     0.073171     0.000000   
50%       0.171171     0.169731     0.096708     0.195122     0.000000   
75%       0.250000     0.216705     0.130916     0.292683     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

            DELINQ        CLAGE         NINQ         CLNO      DEBTINC  \
count  5960.000000  5960.000000  5960.000000  5960.000000  5960.000000   
mean      0.029963     0.153879     0.069768     0.299945     0.163991   
std       0.071400     0.071529     0.097238     0.140117     0.037639   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.100469     0.000000     0.211268     0.149115   
50%       0.000000     0.152432     0.058824     0.295775     0.163991   
75%       0.029963     0.194433     0.117647     0.366197     0.184555   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

       REASON_HomeImp   JOB_Office    JOB_Other  JOB_ProfExe    JOB_Sales  \
count     5960.000000  5960.000000  5960.000000  5960.000000  5960.000000   
mean         0.298658     0.159060     0.447483     0.214094     0.018289   
std          0.457708     0.365763     0.497276     0.410227     0.134004   
min          0.000000     0.000000     0.000000     0.000000     0.000000   
25%          0.000000     0.000000     0.000000     0.000000     0.000000   
50%          0.000000     0.000000     0.000000     0.000000     0.000000   
75%          1.000000     0.000000     1.000000     0.000000     0.000000   
max          1.000000     1.000000     1.000000     1.000000     1.000000   

          JOB_Self  
count  5960.000000  
mean      0.032383  
std       0.177029  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       1.000000

In [ ]:
# generate y and data partipation

y= df['BAD']

from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val=train_test_split(X,y,
                                             test_size=0.3,
                                             random_state=0)

In [ ]:
from sklearn.neural_network import MLPClassifier

NN = MLPClassifier(hidden_layer_sizes=(5,3),max_iter=1000) # first layer 5 and the second layer 3

NN.fit(X_train,y_train)

MLPClassifier(hidden_layer_sizes=(5, 3), max_iter=1000)

In [ ]:
print(NN.coefs_[0])

[[ 1.72014611 -0.57778392 -0.13049546 -0.30412115 -1.3824195 ]
 [ 0.65168591 -0.25780152 -0.64900127 -0.58186922 -1.74354414]
 [ 1.53893418 -0.0919837  -0.77028938  0.48641518 -0.35389243]
 [ 0.80943951  0.1855058   0.39768769  0.24465275 -0.13880825]
 [-1.19192852 -0.31165864  0.42027189  0.62990791  0.28389026]
 [-1.03043192 -1.4225122  -0.81958739  0.92644237 -0.17277041]
 [ 0.57544479  0.13402125  0.54374181 -1.05979092  0.60129117]
 [-1.20533704 -0.26020797 -0.31712185  0.33065391 -0.75724355]
 [ 0.73706231  0.86614531  0.83664737  0.73930229 -0.70360324]
 [-0.82179772 -0.81894964 -0.17945115  1.2256951   0.2557997 ]
 [-0.10618625  0.2927535   0.67604136  0.2556162   0.05476135]
 [ 1.08321326 -0.03887094  0.45327286  0.03729425  0.21020615]
 [ 0.22107027  0.29635793  0.1884148   0.15668164  0.20221331]
 [-0.18190427  0.60166156  0.2072229   0.28283031 -0.2239386 ]
 [ 0.77070482 -0.07799628  0.31165037  0.29209187 -0.37846417]
 [-0.23208009  0.31470946  0.17906494  0.2857586  -0.50

In [ ]:
print(NN.coefs_[1])

[[ 1.07097707e+00  9.82256187e-01 -4.21153218e-01]
 [-5.29514037e-01  8.60435935e-01 -4.45910241e-01]
 [-9.32226790e-01  7.75526138e-01  1.08589505e-03]
 [ 1.55758151e+00 -2.42010041e+00  1.54490039e+00]
 [ 1.22407007e+00 -1.91124202e+00  1.41757339e+00]]


In [ ]:
print(NN.coefs_[2])

[[ 2.23499899]
 [-1.32505012]
 [ 1.47777254]]


In [ ]:
NN.activation
NN.coefs_

[array([[ 1.72014611, -0.57778392, -0.13049546, -0.30412115, -1.3824195 ],
        [ 0.65168591, -0.25780152, -0.64900127, -0.58186922, -1.74354414],
        [ 1.53893418, -0.0919837 , -0.77028938,  0.48641518, -0.35389243],
        [ 0.80943951,  0.1855058 ,  0.39768769,  0.24465275, -0.13880825],
        [-1.19192852, -0.31165864,  0.42027189,  0.62990791,  0.28389026],
        [-1.03043192, -1.4225122 , -0.81958739,  0.92644237, -0.17277041],
        [ 0.57544479,  0.13402125,  0.54374181, -1.05979092,  0.60129117],
        [-1.20533704, -0.26020797, -0.31712185,  0.33065391, -0.75724355],
        [ 0.73706231,  0.86614531,  0.83664737,  0.73930229, -0.70360324],
        [-0.82179772, -0.81894964, -0.17945115,  1.2256951 ,  0.2557997 ],
        [-0.10618625,  0.2927535 ,  0.67604136,  0.2556162 ,  0.05476135],
        [ 1.08321326, -0.03887094,  0.45327286,  0.03729425,  0.21020615],
        [ 0.22107027,  0.29635793,  0.1884148 ,  0.15668164,  0.20221331],
        [-0.18190427,  0.

In [ ]:
# model evaluation
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from matplotlib import pyplot as plt

# confusion matrix
prediction_prob = NN.predict_proba(X_val)
print(NN.score(X_val,y_val)) # accuracy score

# roc curve
nn_auc = roc_auc_score(y_val, prediction_prob[:,1])
print(nn_auc)


0.8417225950782998
0.7906050698962829
